### ISSUE TITLE
Regarding porting

### ISSUE THREAD

**Issue by TheDiamondYT1** [essentials/EssSupport#6]
This has been asked before, but my way will be - different. 

---

I would like to port Essentials to Minecraft: Pocket Edition. Now, I know that I am authorized to do so, so long as I abide by the license. But I was wondering if you wouldn't mind hosting the repo in the essentials organisation?

**How my port will be different to the others, and worth hosting it here**
My port will copy each and every chat message there is. Most of the current ports of Essentials use different or shortened chat mesages.

I will include as many features as possible to two different server software. Yes, you hear me right, [PocketMine-MP](http://github.com/PocketMine/PocketMine-MP) and [RedstoneLamp](http://github.com/RedstoneLamp/RedstoneLamp). 

**What features do you plan to include?**
- /kickall
- /killall
- /god
- /heal
- /feed _(Once hunger is in server softwares)_
- /tpa
- /tpaccept _(And aliases)_
- /tpdeny _(And aliases)_
- /tpall
- /burn
- /ci
- /home
- /sethome
  _The above will be for the first version!_

**Why host it in the essentials organisation on Github?**
The question should be: why not? That way Essentials developers can contribute and people will know its not a scam like some of the ports I've found, as its on the official github.

**_Thanks for reading and please get back to me As Soon As Possible**_

**Comment by necrodoom** [comment]
The main problem with this idea is that many of us do not own copies of pocket edition, so supporting this from the main #essentials channel and testing commits may be a problem. Im not against hosting or calling it official, but the two problems may hurt picking it up from the ground.

**Comment by TheDiamondYT1** [comment]
You do not need to own pocket edition, just have a look through http://github.com/pocketmine/pocketmine-mp, it is similar to bukkit in PHP. However redstonelamp is java but a completely different API to pocketmine or bukkit. I can do that in my own repo, the one here would be PocketMine.

**Comment by iksaku** [comment]
`Bumping this up`

@TheDiamondYT1:
As of PocketMine, [there is a port](https://github.com/LegendOfMCPE/EssentialsPE) (already authorized) with most of the features you are listing.
The only thing we are not currently supporting is the ability to use _Essentials_ configuration files with _EssentialsPE_ as most of the users we currently have, doesn't have any previous experience with Bukkit, or are not currently interested in having the same configuration file.
If you want to get this done, please open an issue inside our [bug tracker](https://github.com/LegendOfMCPE/EssentialsPE/issues) and we will be happy to work with you in that feature.

# 

@necrodoom (\cc @khobbits):
About official support from the team (Hosting the repo in the same Github organization) you told that many of you do not own a Minecraft Pocket Edition copy, but I would love to deeply discuss the idea with the whole team, some things can be done to solve it and the usage of existing code is also an option to "officially" start from (Instead of going from scratch).

**Comment by khobbits** [comment]
I have no issues with porting Essentials to any other platform, or game.

Use of the Essentials code in any way, means you need to abide by the License.  Other than that, there are no restrictions about co-opting the code base.  Currently there are two complete forks of Essentials for Bukkit in major distribution.  My only request about using the code base, is that the project name is differentiated in some way from "Essentials", this can be adding a letter or two to the name, or a complete re-brand.

As for using this Github Account:  As Myself and the core team will be not reviewing the code base of any ports, I do not feel that I could host a repository here, as doing so would be a form of endorsement.  Since I'm not planning on enforcing any creative or quality quality control upon the project, I don't believe it belongs on this account.
